name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        plan:
        - { build: stack, resolver: "--resolver lts-9" }    # ghc-8.0.2
        - { build: stack, resolver: "--resolver lts-11" }   # ghc-8.2.2
        - { build: stack, resolver: "--resolver lts-12" }   # ghc-8.4.4
        - { build: stack, resolver: "--resolver lts-12" }
        - { build: stack, resolver: "--resolver lts-15" }
        - { build: stack, resolver: "--resolver lts-17" }
        - { build: stack, resolver: "--resolver lts-19" }

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup stack
      uses: mstksg/setup-stack@v1

    - name: Install dependencies
      run: stack --no-terminal --install-ghc $ARGS build --bench --only-dependencies
      env:
        ARGS: ${{ matrix.plan.resolver }}

    - name: Build
      run: stack --no-terminal $ARGS build
      env:
        ARGS: ${{ matrix.plan.resolver }}

    - name: Test
      run: stack --no-terminal $ARGS build
      env:
        ARGS: ${{ matrix.plan.resolver }}
